# Generated by Django 6.0.4 on 2026-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
